FROM python:3.6
WORKDIR /code
COPY . .
RUN pip install pipenv
RUN pipenv install --system
RUN curl 'https://media.githubusercontent.com/media/szymonlopaciuk/scrabble/master/scrabble.db' > scrabble.db
CMD python3 /code/wsgi.py